version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: 
          name: "npm install"
          command: sudo npm install
      - run: 
          name: "npm test"
          command: sudo npm run test
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: 
          name: "npm install"
          command: sudo npm install
      - run: 
          name: "npm test"
          command: sudo npm test
workflows:
    build_and_test:
      jobs:
        - test
        - test:
            requires:
              - test