version: 2.1
orbs:
  node: circleci/node@4.7.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: 
          name: "npm install"
          command: sudo npm install
      - run: 
          name: "npm build"
          command: sudo npm run build
  test:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: 
          name: "npm install"
          command: sudo npm install
      - run: 
          name: "npm test"
          command: sudo npm test
workflows:
    build_and_test:
      jobs:
        - test
        - test:
            requires:
              - test